package tokenindex

import (
	"reflect"
	"strings"
	"testing"
)

// indexDoc builds a document shaped like the upstream code skill: prose, the
// Token index section, and a definitions section after the rule whose headings
// carry bracketed markers of their own. Markers are built through brackets so
// this file never holds a literal non-canonical citation for the repo gate
// (lawtokens.TestRepoMarkersAreCanonical scans every tracked file).
func brackets(namespace, token string) string {
	return "[" + namespace + ":" + token + "]"
}

func indexDoc(framings, laws string) string {
	return strings.Join([]string{
		"# THE UNIVERSAL ARCHITECTURAL LAWS",
		"",
		"Cite as `// " + brackets("LAW", "<token>") + " reason`.",
		"",
		"## The token index",
		"",
		"Framings (used in reasoning, not cited in code):",
		framings,
		"",
		"Laws (cited in code as `" + brackets("LAW", "<token>") + "`):",
		laws,
		"",
		"Definitions follow. The index is for lookup; the document is for reading. Read it.",
		"",
		"---",
		"",
		"## " + brackets("LAW", "not-in-the-index") + " - a definition heading",
		"`also-not-in-the-index` · `nor-this`",
	}, "\n")
}

func TestParseReadsBothNamespacesInUpstreamOrder(t *testing.T) {
	doc := indexDoc(
		"`"+brackets("FRAMING", "parts-and-seams")+"` · `"+brackets("FRAMING", "representation")+"`",
		"`decomposition` · `types-are-the-program` ·\n`no-silent-failure`",
	)

	index, err := Parse(doc)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}

	want := []string{
		"FRAMING:parts-and-seams",
		"FRAMING:representation",
		"LAW:decomposition",
		"LAW:types-are-the-program",
		"LAW:no-silent-failure",
	}
	if got := index.Keys(); !reflect.DeepEqual(got, want) {
		t.Errorf("Keys() = %q, want %q", got, want)
	}
}

func TestParseRefusesAnIndexItCannotReadWhole(t *testing.T) {
	framings := "`" + brackets("FRAMING", "representation") + "`"
	laws := "`decomposition` · `no-silent-failure`"

	cases := []struct {
		name    string
		doc     string
		wantErr string
	}{
		{
			name:    "no index heading",
			doc:     strings.Replace(indexDoc(framings, laws), "## The token index", "## Token list", 1),
			wantErr: "no \"## The token index\" heading",
		},
		{
			name:    "index heading twice",
			doc:     indexDoc(framings, laws) + "\n## The token index\n",
			wantErr: "appears more than once",
		},
		{
			name:    "an unknown namespace header",
			doc:     strings.Replace(indexDoc(framings, laws), "Laws (cited", "Rules (cited", 1),
			wantErr: "lists entries under no known namespace header",
		},
		{
			name:    "tokens split off from their header by a blank line",
			doc:     indexDoc(framings, laws+"\n\n`carrying-cost` · `composability`"),
			wantErr: "lists entries under no known namespace header",
		},
		{
			name:    "tokens on the header line",
			doc:     strings.Replace(indexDoc(framings, laws), "`):", "`): `carrying-cost` ·", 1),
			wantErr: "has entries after its colon",
		},
		{
			name:    "a token outside backticks",
			doc:     indexDoc(framings, "`decomposition` · no-silent-failure"),
			wantErr: "has text outside backticked tokens",
		},
		{
			name:    "a miscased token",
			doc:     indexDoc(framings, "`decomposition` · `No-Silent-Failure`"),
			wantErr: "is not a lowercase hyphenated token",
		},
		{
			name:    "a marker from the other namespace",
			doc:     indexDoc("`"+brackets("LAW", "representation")+"`", laws),
			wantErr: "is not a lowercase hyphenated token",
		},
		{
			name:    "an unclosed marker",
			doc:     indexDoc("`[FRAMING:representation`", laws),
			wantErr: "is not a closed marker",
		},
		{
			name:    "a token listed twice",
			doc:     indexDoc(framings, "`decomposition` · `decomposition`"),
			wantErr: "LAW:decomposition is listed twice",
		},
		{
			name:    "a namespace with no tokens",
			doc:     indexDoc(framings, "·"),
			wantErr: "no LAW tokens found",
		},
		{
			name:    "a namespace listed twice",
			doc:     indexDoc(framings, laws+"\n\nLaws (again):\n`carrying-cost`"),
			wantErr: "namespace LAW is listed twice",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := Parse(tc.doc)
			if err == nil {
				t.Fatalf("Parse accepted the document")
			}
			if !strings.Contains(err.Error(), tc.wantErr) {
				t.Errorf("Parse error = %q, want it to contain %q", err, tc.wantErr)
			}
		})
	}
}

// The sync tool's -check compares bytes, so Render's exact output is the
// contract, not just the keys it lists.
func TestRenderListsKeysInOrderAsGoSource(t *testing.T) {
	index, err := Parse(indexDoc(
		"`"+brackets("FRAMING", "representation")+"`",
		"`no-silent-failure` · `decomposition`",
	))
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}

	want := "// Code generated by `go run ./tools/lawtokens-sync`; DO NOT EDIT.\n" +
		"// Source: " + UpstreamURL + "\n" +
		"\n" +
		"package lawtokens\n" +
		"\n" +
		"var canonicalKeys = []string{\n" +
		"\t\"FRAMING:representation\",\n" +
		"\t\"LAW:no-silent-failure\",\n" +
		"\t\"LAW:decomposition\",\n" +
		"}\n"
	if got := string(index.Render()); got != want {
		t.Errorf("Render() =\n%s\nwant\n%s", got, want)
	}
}
