package doccites

import (
	"fmt"
	"io/fs"
	"sort"
	"strings"
)

// Held is one citation that resolved to the symbol its sentence names, at the
// time the manifest was generated.
//
// Keyed on the sentence rather than on a line number. A doc line moves whenever
// anything above it is edited, so a manifest keyed on one would report drift
// every time a chapter gained a paragraph — noise in the exact place this gate
// is asking to be believed.
type Held struct {
	Doc    string
	Text   string
	Symbol string
}

func (h Held) String() string { return fmt.Sprintf("%s %s → %s", h.Doc, h.Text, h.Symbol) }

// Holding reduces a survey to the citations that resolved, deduplicated and
// ordered so that a regenerated manifest differs only where the corpus did.
func Holding(findings []Finding) []Held {
	seen := map[Held]bool{}
	for _, f := range findings {
		if f.Verdict == Holds {
			seen[Held{Doc: f.Doc, Text: f.Text, Symbol: f.Symbol}] = true
		}
	}
	out := make([]Held, 0, len(seen))
	for h := range seen {
		out = append(out, h)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Doc != out[j].Doc {
			return out[i].Doc < out[j].Doc
		}
		if out[i].Text != out[j].Text {
			return out[i].Text < out[j].Text
		}
		return out[i].Symbol < out[j].Symbol
	})
	return out
}

// Lapsed names the manifest entries whose citation no longer resolves.
//
// One direction only, and deliberately. Every entry recorded as holding must
// still hold; a chapter is never required to keep any particular citation, so
// deleting a sentence or rewriting a citation to name a different symbol is an
// ordinary edit that regenerating absorbs. What cannot pass is a citation that
// pointed at its subject and stopped — which is what an edit to the cited file
// does, silently, to every citation below the change.
func Lapsed(manifest []Held, findings []Finding) []Held {
	now := map[Held]bool{}
	for _, h := range Holding(findings) {
		now[h] = true
	}
	var out []Held
	for _, h := range manifest {
		if !now[h] {
			out = append(out, h)
		}
	}
	return out
}

// Explain says what a contributor has to do about one lapsed entry, which is
// not always the same thing.
func Explain(h Held, findings []Finding) string {
	for _, f := range findings {
		if f.Doc == h.Doc && f.Text == h.Text {
			switch f.Verdict {
			case Moved:
				return fmt.Sprintf("%s:%d: %s no longer brackets `%s`, which is now at %s:%d — repoint the citation",
					f.Doc, f.DocLine, f.Text, h.Symbol, f.File, f.Declared)
			case PastEOF:
				return fmt.Sprintf("%s:%d: %s now runs past the end of a %d-line %s — repoint the citation",
					f.Doc, f.DocLine, f.Text, f.Declared, f.File)
			case Unresolved:
				return fmt.Sprintf("%s:%d: %s no longer identifies one file in this tree — repoint the citation",
					f.Doc, f.DocLine, f.Text)
			}
		}
	}
	// The sentence itself is gone, which is an ordinary edit rather than drift.
	return fmt.Sprintf("%s: %s is no longer in the chapter — regenerate with `go run ./tools/doccites -sync`", h.Doc, h.Text)
}

// Render writes the manifest as Go source.
func Render(held []Held) string {
	var b strings.Builder
	b.WriteString("// Code generated by `go run ./tools/doccites -sync`. DO NOT EDIT.\n\n")
	b.WriteString("package doccites\n\n")
	b.WriteString("// Manifest records every citation that resolved to the symbol its sentence\n")
	b.WriteString("// names, as of the last regeneration. TestCitationsStillResolve holds the\n")
	b.WriteString("// corpus to it: an entry that stops resolving is a chapter pointing a reader\n")
	b.WriteString("// at code that is no longer what it describes.\n")
	b.WriteString("var Manifest = []Held{\n")
	for _, h := range held {
		fmt.Fprintf(&b, "\t{Doc: %q, Text: %q, Symbol: %q},\n", h.Doc, h.Text, h.Symbol)
	}
	b.WriteString("}\n")
	return b.String()
}

// Regenerate surveys the corpus and returns the manifest source for it.
func Regenerate(root fs.FS) (string, error) {
	findings, err := Survey(root)
	if err != nil {
		return "", err
	}
	return Render(Holding(findings)), nil
}
