package store

import (
	"context"
	"database/sql"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/pmezard/go-difflib/difflib"
)

// updateSchemaSnapshot regenerates the checked-in snapshot from the live
// converged schema instead of comparing against it. Drift detection is
// intentional friction: a developer who changed the schema through a migration
// runs this to refresh the golden file, reviews the diff, and commits it.
var updateSchemaSnapshot = flag.Bool("update-schema-snapshot", false,
	"regenerate internal/store/schema_snapshot.sql from the converged schema")

// schemaSnapshotFile is the golden file, resolved relative to the package
// directory (go test runs with the cwd set there).
const schemaSnapshotFile = "schema_snapshot.sql"

// schemaSnapshotHeader prefaces the golden file. It is part of the compared
// document, so a hand-edit that strips the warning is itself drift.
const schemaSnapshotHeader = `-- schema_snapshot.sql — GENERATED, DO NOT HAND-EDIT.
--
-- Canonical SHOW CREATE TABLE of every application table after a fresh
-- workspace applies the goose registry (00001_baseline.sql + any later
-- migrations). The drift canary regenerates this and byte-compares; a mismatch
-- means the schema reached the database through something other than a
-- migration, or a migration changed shape without this snapshot being refreshed.
--
-- Regenerate:
--   go test ./internal/store -run TestSchemaSnapshotMatchesConvergedSchema -update-schema-snapshot
--
-- goose_db_version is intentionally excluded: it is goose's bookkeeping table,
-- not application schema, and its AUTO_INCREMENT counter is not deterministic.`

// TestSchemaSnapshotMatchesConvergedSchema is the drift canary. A fresh
// workspace applies the goose registry; its serialized schema must equal the
// checked-in snapshot byte-for-byte. The comparison is symmetric over the whole
// document, so an extra/leftover table, a missing table, or a changed shape all
// fail identically — there is no per-expected-table loop that could overlook an
// unexpected table.
//
// [LAW:one-source-of-truth] The snapshot is derived from the migration registry
// and regenerated by -update-schema-snapshot; it is never hand-maintained, so
// the registry stays the sole authority on schema shape.
func TestSchemaSnapshotMatchesConvergedSchema(t *testing.T) {
	got := dumpFreshWorkspaceSchema(t)

	if *updateSchemaSnapshot {
		if err := os.WriteFile(schemaSnapshotFile, []byte(got), 0o644); err != nil {
			t.Fatalf("write snapshot: %v", err)
		}
		t.Logf("regenerated %s", schemaSnapshotFile)
		return
	}

	wantBytes, err := os.ReadFile(schemaSnapshotFile)
	if err != nil {
		t.Fatalf("read %s: %v\nregenerate with: go test ./internal/store -run %s -update-schema-snapshot",
			schemaSnapshotFile, err, t.Name())
	}
	if got != string(wantBytes) {
		t.Fatalf("schema drift: the converged schema no longer matches %s\n\n%s\n"+
			"If this change is intended, route it through a migration in "+
			"internal/store/migrations and regenerate:\n"+
			"  go test ./internal/store -run %s -update-schema-snapshot",
			schemaSnapshotFile, unifiedSchemaDiff(string(wantBytes), got), t.Name())
	}
}

// TestConvergedSchemaDumpIsDeterministic pins the property the baseline relies
// on (explicit constraint names so SHOW CREATE TABLE is stable across applies):
// two independently migrated fresh workspaces must serialize identically. If a
// Dolt upgrade ever introduces volatility, it fails loudly here rather than as
// a flaky drift comparison.
func TestConvergedSchemaDumpIsDeterministic(t *testing.T) {
	first := dumpFreshWorkspaceSchema(t)
	second := dumpFreshWorkspaceSchema(t)
	if first != second {
		t.Fatalf("converged-schema dump is not deterministic across fresh workspaces:\n%s",
			unifiedSchemaDiff(first, second))
	}
}

// TestConvergedSchemaDumpIncludesUnexpectedTables locks the property sxsk.2's
// adoption gate intentionally leaves open: it does not reject a workspace
// carrying a leftover table the baseline removed. The drift canary closes that
// gap only if its dump enumerates every table actually present — so an
// unexpected table must appear in the dump and break the byte-compare.
func TestConvergedSchemaDumpIncludesUnexpectedTables(t *testing.T) {
	ctx := context.Background()
	st := openFreshWorkspace(t)
	if err := st.ExecRawForTest(ctx, `CREATE TABLE leftover_legacy (id VARCHAR(191) PRIMARY KEY)`); err != nil {
		t.Fatalf("create leftover table: %v", err)
	}
	got, err := dumpConvergedSchema(ctx, st.db)
	if err != nil {
		t.Fatalf("dump: %v", err)
	}
	if !strings.Contains(got, "leftover_legacy") {
		t.Fatal("dump omitted an unexpected table; the canary would not catch a leftover/extra table")
	}
}

// dumpConvergedSchema serializes the application schema: every table the active
// database holds except goose's bookkeeping table, in sorted order, each as its
// verbatim SHOW CREATE TABLE terminated with a semicolon. Verbatim (no
// normalization) is deliberate — determinism is enforced upstream by the
// baseline's explicit constraint names, and a Dolt formatting change is real
// drift this canary should surface, not hide.
func dumpConvergedSchema(ctx context.Context, db *sql.DB) (string, error) {
	tables, err := applicationTables(ctx, db)
	if err != nil {
		return "", err
	}
	blocks := make([]string, 0, len(tables))
	for _, table := range tables {
		ddl, err := showCreateTable(ctx, db, table)
		if err != nil {
			return "", err
		}
		blocks = append(blocks, ddl+";")
	}
	return schemaSnapshotHeader + "\n\n" + strings.Join(blocks, "\n\n") + "\n", nil
}

// applicationTables lists the active database's tables minus goose's version
// table, sorted. Enumerating from the live database (not a fixed list) is what
// lets the canary catch unexpected tables.
func applicationTables(ctx context.Context, db *sql.DB) ([]string, error) {
	rows, err := db.QueryContext(ctx,
		`SELECT table_name FROM information_schema.tables WHERE table_schema = DATABASE()`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var tables []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		if name == gooseVersionTable {
			continue
		}
		tables = append(tables, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	sort.Strings(tables)
	return tables, nil
}

// showCreateTable returns Dolt's canonical CREATE statement for one table. The
// table name cannot be a bound parameter in SHOW CREATE TABLE, so it is escaped
// and backtick-quoted — the canonical way to interpolate an identifier, valid
// for any table name the database reports rather than only backtick-free ones.
func showCreateTable(ctx context.Context, db *sql.DB, table string) (string, error) {
	var name, ddl string
	quoted := "`" + strings.ReplaceAll(table, "`", "``") + "`"
	if err := db.QueryRowContext(ctx, "SHOW CREATE TABLE "+quoted).Scan(&name, &ddl); err != nil {
		return "", err
	}
	return ddl, nil
}

func unifiedSchemaDiff(want, got string) string {
	out, err := difflib.GetUnifiedDiffString(difflib.UnifiedDiff{
		A:        difflib.SplitLines(want),
		B:        difflib.SplitLines(got),
		FromFile: schemaSnapshotFile + " (checked in)",
		ToFile:   "live converged schema",
		Context:  3,
	})
	if err != nil {
		// A failed diff must not collapse to an empty string — the drift would
		// then be invisible. Surface the error and the full documents instead.
		return fmt.Sprintf("(unified diff unavailable: %v)\n--- want ---\n%s\n--- got ---\n%s", err, want, got)
	}
	return out
}

func openFreshWorkspace(t *testing.T) *Store {
	t.Helper()
	doltRoot := filepath.Join(t.TempDir(), "dolt")
	st, err := Open(context.Background(), doltRoot, "drift-canary")
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	t.Cleanup(func() { _ = st.Close() })
	return st
}

func dumpFreshWorkspaceSchema(t *testing.T) string {
	t.Helper()
	st := openFreshWorkspace(t)
	got, err := dumpConvergedSchema(context.Background(), st.db)
	if err != nil {
		t.Fatalf("dump: %v", err)
	}
	return got
}
