// Code generated by `go run ./tools/lawtokens-sync`; DO NOT EDIT.
// Source: https://raw.githubusercontent.com/promptctl/laws/master/plugins/laws/skills/code/SKILL.md

package lawtokens

var canonicalKeys = []string{
	"FRAMING:parts-and-seams",
	"FRAMING:representation",
	"LAW:decomposition",
	"LAW:types-are-the-program",
	"LAW:composability",
	"LAW:carrying-cost",
	"LAW:polishing-by-subtraction",
	"LAW:no-ambient-temporal-coupling",
	"LAW:effects-at-boundaries",
	"LAW:one-source-of-truth",
	"LAW:single-enforcer",
	"LAW:comments-carry-meaning",
	"LAW:dataflow-not-control-flow",
	"LAW:one-type-per-behavior",
	"LAW:no-mode-explosion",
	"LAW:parse-dont-validate",
	"LAW:no-defensive-null-guards",
	"LAW:locality-or-seam",
	"LAW:one-way-deps",
	"LAW:no-shared-mutable-globals",
	"LAW:verifiable-goals",
	"LAW:behavior-not-structure",
	"LAW:no-silent-failure",
}
