package lawtokens

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

// UpstreamIndexURL is where the Token index Canonical is generated from: the
// code skill of the universal-laws plugin, published at github.com/promptctl/laws.
// tools/lawtokens-sync fetches it, and nothing else in the tree names it.
const UpstreamIndexURL = "https://raw.githubusercontent.com/promptctl/laws/master/plugins/laws/skills/code/SKILL.md"

// indexHeading is the line that opens the Token index section in the upstream
// document. The section runs to the next heading or horizontal rule.
const indexHeading = "## The token index"

// namespaces pairs each marker namespace with the paragraph header that lists
// its tokens in the upstream index. It is the one list of namespaces in the
// package: markerPattern is built from it too, so a namespace cannot be
// scannable without being parseable, or the reverse. [LAW:one-source-of-truth]
var namespaces = []struct {
	name   string
	header string
}{
	{name: "FRAMING", header: "Framings ("},
	{name: "LAW", header: "Laws ("},
}

var (
	indexSpan  = regexp.MustCompile("`([^`]*)`")
	indexToken = regexp.MustCompile(`^[a-z]+(-[a-z]+)*$`)
)

// Index is a Token index that parsed: every namespace present, every token
// well-formed, no key twice. Its keys keep upstream order, so the generated
// file reads in the same order as the document it came from.
// [LAW:parse-dont-validate] only ParseIndex makes one, so Render can only ever
// emit a list that passed these checks.
type Index struct {
	keys []string
}

// Keys returns the "NAMESPACE:token" keys in upstream order.
func (ix Index) Keys() []string {
	return append([]string(nil), ix.keys...)
}

// ParseIndex reads the Token index section out of the upstream document.
//
// Each namespace's tokens are the paragraph under its header, as backticked
// spans separated by " · ". A span is either a bare token or the full
// bracketed marker in that paragraph's namespace. Anything else on a token
// line is an error rather than something to skip: a format change upstream
// has to stop the sync, not quietly drop tokens. [LAW:no-silent-failure]
func ParseIndex(doc string) (Index, error) {
	section, err := indexSection(doc)
	if err != nil {
		return Index{}, err
	}

	byNamespace := map[string][]string{}
	for _, para := range paragraphs(section) {
		header, body := para[0], para[1:]
		ns, ok := namespaceFor(header)
		if !ok {
			// Prose, such as the "Definitions follow" line. A backticked entry
			// here would be a token no namespace claims, so it is refused.
			if strings.Contains(strings.Join(para, "\n"), "`") {
				return Index{}, fmt.Errorf("token index: paragraph %q lists entries under no known namespace header", header)
			}
			continue
		}
		if !strings.HasSuffix(header, ":") {
			return Index{}, fmt.Errorf("token index: %s header %q has entries after its colon; tokens belong on the lines below it", ns, header)
		}
		if _, seen := byNamespace[ns]; seen {
			return Index{}, fmt.Errorf("token index: namespace %s is listed twice", ns)
		}
		tokens, err := parseTokenLines(ns, body)
		if err != nil {
			return Index{}, err
		}
		byNamespace[ns] = tokens
	}

	var keys []string
	seen := map[string]bool{}
	for _, ns := range namespaces {
		tokens := byNamespace[ns.name]
		if len(tokens) == 0 {
			return Index{}, fmt.Errorf("token index: no %s tokens found under a %q header", ns.name, ns.header+"...)")
		}
		for _, token := range tokens {
			key := ns.name + ":" + token
			if seen[key] {
				return Index{}, fmt.Errorf("token index: %s is listed twice", key)
			}
			seen[key] = true
			keys = append(keys, key)
		}
	}
	return Index{keys: keys}, nil
}

// Render is the Go source of canonical_gen.go for this index.
func (ix Index) Render() []byte {
	var b strings.Builder
	b.WriteString("// Code generated by `go run ./tools/lawtokens-sync`; DO NOT EDIT.\n")
	b.WriteString("// Source: " + UpstreamIndexURL + "\n\n")
	b.WriteString("package lawtokens\n\n")
	b.WriteString("var canonicalKeys = []string{\n")
	for _, key := range ix.keys {
		b.WriteString("\t" + strconv.Quote(key) + ",\n")
	}
	b.WriteString("}\n")
	return []byte(b.String())
}

func indexSection(doc string) ([]string, error) {
	lines := strings.Split(doc, "\n")
	start := -1
	for i, line := range lines {
		if strings.TrimRight(line, " \r") == indexHeading {
			if start >= 0 {
				return nil, fmt.Errorf("token index: %q appears more than once", indexHeading)
			}
			start = i + 1
		}
	}
	if start < 0 {
		return nil, fmt.Errorf("token index: no %q heading in the document", indexHeading)
	}
	end := len(lines)
	for i := start; i < len(lines); i++ {
		trimmed := strings.TrimSpace(lines[i])
		if strings.HasPrefix(trimmed, "#") || trimmed == "---" {
			end = i
			break
		}
	}
	return lines[start:end], nil
}

func paragraphs(lines []string) [][]string {
	var out [][]string
	var cur []string
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			if len(cur) > 0 {
				out = append(out, cur)
			}
			cur = nil
			continue
		}
		cur = append(cur, trimmed)
	}
	if len(cur) > 0 {
		out = append(out, cur)
	}
	return out
}

func namespaceFor(header string) (string, bool) {
	for _, ns := range namespaces {
		if strings.HasPrefix(header, ns.header) {
			return ns.name, true
		}
	}
	return "", false
}

func parseTokenLines(ns string, lines []string) ([]string, error) {
	var tokens []string
	for _, line := range lines {
		rest := strings.TrimSpace(strings.ReplaceAll(indexSpan.ReplaceAllString(line, ""), "·", ""))
		if rest != "" {
			return nil, fmt.Errorf("token index: %s line %q has text outside backticked tokens: %q", ns, line, rest)
		}
		for _, m := range indexSpan.FindAllStringSubmatch(line, -1) {
			token := m[1]
			if inner, ok := strings.CutPrefix(token, "["+ns+":"); ok {
				token, ok = strings.CutSuffix(inner, "]")
				if !ok {
					return nil, fmt.Errorf("token index: %s entry `%s` is not a closed marker", ns, m[1])
				}
			}
			if !indexToken.MatchString(token) {
				return nil, fmt.Errorf("token index: %s entry `%s` is not a lowercase hyphenated token", ns, m[1])
			}
			tokens = append(tokens, token)
		}
	}
	return tokens, nil
}
