package main

import (
	"fmt"
	"strings"
	"text/tabwriter"
	"time"
)

// result is one store's complete measurement: its size, its bytes on disk, and
// one sample per probe.
type result struct {
	size    size
	bytes   int64
	samples []sample
}

// conditions is the machine the run happened on. It is passed in rather than
// read here so the report stays a pure function of its inputs and its tests
// need no machine to agree with. [LAW:effects-at-boundaries]
type conditions struct {
	goos   string
	goarch string
	cpus   int
}

// renderReport turns measurements into the table, and is deliberately the only
// part of this tool that decides what the output looks like — no subprocess, no
// clock, no filesystem, so the format is testable against fixed samples rather
// than against a store somebody has to build first. [LAW:effects-at-boundaries]
//
// Sizes are columns and probes are rows because the question the scale epic asks
// is how a command's cost moves with the store: reading across one row answers
// it directly, and a per-size block layout would make the reader hold three
// numbers in their head to see it.
func renderReport(results []result, cond conditions) string {
	var b strings.Builder
	fmt.Fprintf(&b, "lit perfbench — %s/%s, %d CPUs\n", cond.goos, cond.goarch, cond.cpus)
	fmt.Fprintf(&b, "%d repeats per probe, round-robin; the figure is the MIN, the max is in parentheses.\n", repeats)
	b.WriteString("A max near the min is a quiet machine and a trustworthy figure. A max several\n")
	b.WriteString("times the min means the run was competing for CPU and only the min survived it.\n")
	b.WriteString("Stores are generated by `lit init` + `lit import`; the binary is built from the\n")
	b.WriteString("working tree, never taken from PATH.\n\n")

	w := tabwriter.NewWriter(&b, 0, 0, 2, ' ', 0)
	fmt.Fprint(w, "COMMAND")
	for _, r := range results {
		fmt.Fprintf(w, "\t%s (%d rows)", r.size.name, r.size.rows)
	}
	fmt.Fprintln(w)

	// Probe order is taken from the first result rather than from the package
	// list so the rows print in the order they were measured — reads first,
	// then the write — which is the order the timings are only valid in.
	for i, name := range probeNames(results) {
		fmt.Fprint(w, name)
		for _, r := range results {
			s := r.samples[i]
			fmt.Fprintf(w, "\t%s (%s)", formatDuration(s.min), formatDuration(s.max))
		}
		fmt.Fprintln(w)
	}
	fmt.Fprint(w, "store bytes")
	for _, r := range results {
		fmt.Fprintf(w, "\t%s", formatBytes(r.bytes))
	}
	fmt.Fprintln(w)
	w.Flush()
	return b.String()
}

// probeNames reads the measured probe order off the results. An empty results
// list has no order to read, which is why it yields none rather than falling
// back to the package-level probes list: a report over nothing must print
// nothing, not a header row of names no column was measured for.
func probeNames(results []result) []string {
	if len(results) == 0 {
		return nil
	}
	names := make([]string, 0, len(results[0].samples))
	for _, s := range results[0].samples {
		names = append(names, s.probe.name)
	}
	return names
}

// formatDuration prints seconds to two decimals, matching the units the scale
// epic states its own figures in ("lit backlog 7.97s") so a regenerated table
// can be compared to the pasted one without converting anything. Sub-second
// costs are the point of the epic, and 0.07s reads as a fraction of a budget in
// a way 70ms does not.
func formatDuration(d time.Duration) string {
	return fmt.Sprintf("%.2fs", d.Seconds())
}

// formatBytes prints against the epic's own 50 MB ceiling and its 188 MB
// observation, both stated in MB. Decimal MB, not MiB: the figures this is
// compared against came from `du`-style reporting, and silently switching base
// would move every number by 5%.
//
// Below a megabyte it switches to KB, which costs a little column scannability
// and buys the empty store an honest figure. The empty store is the control for
// lit's fixed on-disk cost, and at two decimals of MB every such store prints
// "0.00 MB" — a real four-kilobyte number rendered as zero, which is the one
// reading a reader must not take from it. Nothing near the ceiling the epic
// cares about is affected: those all print in MB.
func formatBytes(n int64) string {
	if n < 1e6 {
		return fmt.Sprintf("%.2f KB", float64(n)/1e3)
	}
	return fmt.Sprintf("%.2f MB", float64(n)/1e6)
}
