// docclaims-sync regenerates internal/docclaims/manifest_gen.go: the record of
// which quoted message literals in doc-v1-total were last seen to match code
// that actually ships.
//
// Run it from the repository root after deliberately changing a documented
// message:
//
//	go run ./tools/docclaims-sync
//
// The diff it produces is the point. An entry that disappears is a sentence in
// the specification that no longer describes the binary, and reviewing that
// diff is how the chapter and the code are re-tied. Regenerating to silence
// TestDocumentedClaimsStillShip without reading what left the manifest is the
// one use that defeats the gate.
//
// Unlike tools/lawtokens-sync this reads only the working tree — no network, so
// it behaves the same in CI, in a container, and on a laptop offline.
package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/promptctl/links-issue-tracker/internal/docclaims"
)

const manifestPath = "internal/docclaims/manifest_gen.go"

// check reports whether to verify the committed manifest instead of rewriting
// it, without writing: the form to reach for in a script, or before committing
// a regeneration.
//
// It is not what guards CI. TestManifestIsCurrent asks the same question on
// every run and is the single enforcer of it; a nightly job running this flag
// would be a second answer to one question, which is the shape of drift this
// package exists to remove. What it adds is a check you can run deliberately —
// the omission it covers is real, since a manifest generated over a dirty
// working tree carrying a gitignored vendored project was committed once and
// broke every clean checkout. [LAW:single-enforcer]
var check = flag.Bool("check", false, "verify the committed manifest matches a regeneration; write nothing")

func main() {
	flag.Parse()
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "docclaims-sync:", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := os.Getwd()
	if err != nil {
		return err
	}

	// Derived against the committed manifest so an entry keeps the source it
	// was anchored to while that source still carries the quotation. Without
	// it, any shorter literal added anywhere retargets unrelated entries.
	matched, err := docclaims.Derive(os.DirFS(root), docclaims.Manifest)
	if err != nil {
		return err
	}
	if len(matched) == 0 {
		// An empty manifest turns the gate off while leaving every sign of it
		// in place, which is worse than failing. [LAW:no-silent-failure]
		return fmt.Errorf("no documented quotation matched shipped text; refusing to trust an empty derivation")
	}

	if *check {
		corpus, err := docclaims.ShippedText(os.DirFS(root))
		if err != nil {
			return err
		}
		return verify(matched, corpus)
	}

	if err := os.WriteFile(manifestPath, []byte(render(matched)), 0o644); err != nil {
		return err
	}
	fmt.Printf("docclaims-sync: %d documented quotations across %d files -> %s\n",
		len(matched), countDocs(matched), manifestPath)
	return nil
}

func countDocs(claims []docclaims.Claim) int {
	seen := map[string]bool{}
	for _, c := range claims {
		seen[c.Doc] = true
	}
	return len(seen)
}

func render(claims []docclaims.Claim) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/docclaims-sync. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Each entry is a message literal that doc-v1-total quotes and that was\n")
	b.WriteString("// present in the shipped Go at the time of generation. TestDocumentedClaimsStillShip\n")
	b.WriteString("// fails when one of them no longer ships, which is a chapter describing a\n")
	b.WriteString("// message the binary no longer has.\n\n")
	b.WriteString("package docclaims\n\n")
	b.WriteString("// Manifest is the documented-literal record. Regenerate with\n")
	b.WriteString("// `go run ./tools/docclaims-sync`; never hand-edit.\n")
	b.WriteString("var Manifest = []Claim{\n")
	for _, c := range claims {
		fmt.Fprintf(&b, "\t{Doc: %s, Text: %s, Src: %s},\n",
			strconv.Quote(c.Doc), strconv.Quote(c.Text), strconv.Quote(c.Src))
	}
	b.WriteString("}\n")
	return b.String()
}

// verify compares the committed manifest against a fresh derivation and names
// the entries that differ, in both directions, rather than only reporting that
// they do.
func verify(want []docclaims.Claim, corpus docclaims.Corpus) error {
	got := docclaims.Manifest
	only := docclaims.Diff(want, got)
	drifted := docclaims.Drifted(got, want, corpus)
	if len(only) == 0 && len(drifted) == 0 {
		fmt.Printf("docclaims-sync: manifest is current (%d quotations)\n", len(got))
		return nil
	}
	for _, c := range only {
		fmt.Fprintf(os.Stderr, "  only in a fresh derivation: %s %q\n", c.Doc, c.Text)
	}
	// Each line carries its own instruction, from the same Explain the
	// freshness test prints, because two reports of one failure that word the
	// remedy differently are how a contributor learns to ignore both.
	count := map[docclaims.DriftKind]int{}
	for _, d := range drifted {
		count[d.Kind]++
		fmt.Fprintf(os.Stderr, "  %s\n", d.Explain())
	}
	// The exit line says which of the three happened, because only one of them
	// has a remedy a contributor can apply without reading anything, and it is
	// not either of the other two.
	switch {
	case count[docclaims.Stopped] > 0:
		return fmt.Errorf("%d documented message(s) no longer ship: fix the code or the chapter. Regenerating would drop them and leave the specification false",
			count[docclaims.Stopped])
	case count[docclaims.AnchorMoved] > 0:
		return fmt.Errorf("%d documented message(s) are no longer carried by the source they were recorded against: read the lines above and confirm each is the same message reworded before regenerating",
			count[docclaims.AnchorMoved])
	}
	return fmt.Errorf("manifest is stale: committed %d quotations, the tree yields %d; run `go run ./tools/docclaims-sync`",
		len(got), len(want))
}
