// docclaims-sync regenerates internal/docclaims/manifest_gen.go: the record of
// which quoted message literals in doc-v1-total were last seen to match code
// that actually ships.
//
// Run it from the repository root after deliberately changing a documented
// message:
//
//	go run ./tools/docclaims-sync
//
// The diff it produces is the point. An entry that disappears is a sentence in
// the specification that no longer describes the binary, and reviewing that
// diff is how the chapter and the code are re-tied. Regenerating to silence
// TestDocumentedClaimsStillShip without reading what left the manifest is the
// one use that defeats the gate.
//
// Unlike tools/lawtokens-sync this reads only the working tree — no network, so
// it behaves the same in CI, in a container, and on a laptop offline.
package main

import (
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/promptctl/links-issue-tracker/internal/docclaims"
)

const manifestPath = "internal/docclaims/manifest_gen.go"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "docclaims-sync:", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := os.Getwd()
	if err != nil {
		return err
	}
	fsys := os.DirFS(root)

	shipped, err := docclaims.ShippedLiterals(fsys)
	if err != nil {
		return err
	}
	names, err := docclaims.SpecFiles(fsys)
	if err != nil {
		return err
	}
	claims, err := docclaims.DocClaims(fsys, names)
	if err != nil {
		return err
	}

	matched := dedupe(docclaims.Matched(claims, shipped))
	if len(matched) == 0 {
		// Writing an empty manifest would turn the gate off while leaving every
		// sign of it in place, which is worse than failing. [LAW:no-silent-failure]
		return fmt.Errorf("no documented literal matched shipped code; refusing to write an empty manifest to %s", manifestPath)
	}

	if err := os.WriteFile(manifestPath, []byte(render(matched)), 0o644); err != nil {
		return err
	}
	fmt.Printf("docclaims-sync: %d documented literals across %d files -> %s\n",
		len(matched), countDocs(matched), manifestPath)
	return nil
}

// dedupe sorts by document then text and drops repeats, so the generated file
// is a function of the tree alone and a re-run with no source change produces
// no diff. [LAW:dataflow-not-control-flow]
func dedupe(claims []docclaims.Claim) []docclaims.Claim {
	sort.Slice(claims, func(i, j int) bool {
		if claims[i].Doc != claims[j].Doc {
			return claims[i].Doc < claims[j].Doc
		}
		return claims[i].Text < claims[j].Text
	})
	var out []docclaims.Claim
	for i, c := range claims {
		if i > 0 && claims[i-1] == c {
			continue
		}
		out = append(out, c)
	}
	return out
}

func countDocs(claims []docclaims.Claim) int {
	seen := map[string]bool{}
	for _, c := range claims {
		seen[c.Doc] = true
	}
	return len(seen)
}

func render(claims []docclaims.Claim) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/docclaims-sync. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Each entry is a message literal that doc-v1-total quotes and that was\n")
	b.WriteString("// present in the shipped Go at the time of generation. TestDocumentedClaimsStillShip\n")
	b.WriteString("// fails when one of them no longer ships, which is a chapter describing a\n")
	b.WriteString("// message the binary no longer has.\n\n")
	b.WriteString("package docclaims\n\n")
	b.WriteString("// Manifest is the documented-literal record. Regenerate with\n")
	b.WriteString("// `go run ./tools/docclaims-sync`; never hand-edit.\n")
	b.WriteString("var Manifest = []Claim{\n")
	for _, c := range claims {
		fmt.Fprintf(&b, "\t{Doc: %s, Text: %s},\n", strconv.Quote(c.Doc), strconv.Quote(c.Text))
	}
	b.WriteString("}\n")
	return b.String()
}
