// docclaims-sync regenerates internal/docclaims/manifest_gen.go: the record of
// which quoted message literals in doc-v1-total were last seen to match code
// that actually ships.
//
// Run it from the repository root after deliberately changing a documented
// message:
//
//	go run ./tools/docclaims-sync
//
// The diff it produces is the point. An entry that disappears is a sentence in
// the specification that no longer describes the binary, and reviewing that
// diff is how the chapter and the code are re-tied. Regenerating to silence
// TestDocumentedClaimsStillShip without reading what left the manifest is the
// one use that defeats the gate.
//
// Unlike tools/lawtokens-sync this reads only the working tree — no network, so
// it behaves the same in CI, in a container, and on a laptop offline.
package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/promptctl/links-issue-tracker/internal/docclaims"
)

const manifestPath = "internal/docclaims/manifest_gen.go"

// check reports whether to verify the committed manifest instead of rewriting
// it. The nightly workflow runs tools/lawtokens-sync the same way; without an
// equivalent here nothing compares what is committed against what the tree
// would produce, which is exactly how a manifest generated over a dirty working
// tree — one carrying a gitignored vendored project — was committed and broke
// CI in a clean checkout. [LAW:single-enforcer]
var check = flag.Bool("check", false, "verify the committed manifest matches a regeneration; write nothing")

func main() {
	flag.Parse()
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "docclaims-sync:", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := os.Getwd()
	if err != nil {
		return err
	}
	fsys := os.DirFS(root)

	shipped, err := docclaims.ShippedLiterals(fsys)
	if err != nil {
		return err
	}
	names, err := docclaims.SpecFiles(fsys)
	if err != nil {
		return err
	}
	claims, err := docclaims.DocClaims(fsys, names)
	if err != nil {
		return err
	}

	matched := docclaims.Dedupe(docclaims.Matched(claims, shipped))
	if len(matched) == 0 {
		// Writing an empty manifest would turn the gate off while leaving every
		// sign of it in place, which is worse than failing. [LAW:no-silent-failure]
		return fmt.Errorf("no documented literal matched shipped code; refusing to write an empty manifest to %s", manifestPath)
	}

	if *check {
		return verify(matched)
	}

	if err := os.WriteFile(manifestPath, []byte(render(matched)), 0o644); err != nil {
		return err
	}
	fmt.Printf("docclaims-sync: %d documented literals across %d files -> %s\n",
		len(matched), countDocs(matched), manifestPath)
	return nil
}

func countDocs(claims []docclaims.Claim) int {
	seen := map[string]bool{}
	for _, c := range claims {
		seen[c.Doc] = true
	}
	return len(seen)
}

func render(claims []docclaims.Claim) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/docclaims-sync. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Each entry is a message literal that doc-v1-total quotes and that was\n")
	b.WriteString("// present in the shipped Go at the time of generation. TestDocumentedClaimsStillShip\n")
	b.WriteString("// fails when one of them no longer ships, which is a chapter describing a\n")
	b.WriteString("// message the binary no longer has.\n\n")
	b.WriteString("package docclaims\n\n")
	b.WriteString("// Manifest is the documented-literal record. Regenerate with\n")
	b.WriteString("// `go run ./tools/docclaims-sync`; never hand-edit.\n")
	b.WriteString("var Manifest = []Claim{\n")
	for _, c := range claims {
		fmt.Fprintf(&b, "\t{Doc: %s, Text: %s, Lit: %s},\n",
			strconv.Quote(c.Doc), strconv.Quote(c.Text), strconv.Quote(c.Lit))
	}
	b.WriteString("}\n")
	return b.String()
}

// verify compares the committed manifest against a fresh derivation and names
// the first entries that differ, rather than only reporting that they do.
func verify(want []docclaims.Claim) error {
	got := docclaims.Manifest
	if len(got) == len(want) {
		same := true
		for i := range got {
			if got[i] != want[i] {
				same = false
				break
			}
		}
		if same {
			fmt.Printf("docclaims-sync: manifest is current (%d literals)\n", len(got))
			return nil
		}
	}
	for _, c := range diff(want, got) {
		fmt.Fprintf(os.Stderr, "  only in a fresh derivation: %s %q\n", c.Doc, c.Text)
	}
	for _, c := range diff(got, want) {
		fmt.Fprintf(os.Stderr, "  only in the committed manifest: %s %q\n", c.Doc, c.Text)
	}
	return fmt.Errorf("manifest is stale: committed %d literals, the tree yields %d; run `go run ./tools/docclaims-sync`",
		len(got), len(want))
}

// diff returns the entries of a that are absent from b.
func diff(a, b []docclaims.Claim) []docclaims.Claim {
	in := make(map[docclaims.Claim]bool, len(b))
	for _, c := range b {
		in[c] = true
	}
	var out []docclaims.Claim
	for _, c := range a {
		if !in[c] {
			out = append(out, c)
		}
	}
	return out
}
